name: API testing
on: push
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout sources
          uses: actions/checkout@v4
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: 17
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v3
        - name: Checkout
          run: git clone https://bitbucket.org/thiagohcn/customer-data-api-java.git
        - name: Run API
          run: cd customer-data-api-java && make run-local
    cypress-run:
        needs: build
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          # Install npm dependencies, cache them correctly
          # and run all Cypress tests
          - name: Cypress run
            uses: cypress-io/github-action@v6
            with:
              command: npm run test
              wait-on: 'http://localhost:8080'